# WeatherApp Deployment
# --------------------
# - Deployment to launch container of rehanalhasan/weatherapp:latest in a pod.
# - Service (type: LoadBalancer) to open up the app to the world (localhost, at least) at port 80.
# 
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    app: weatherapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: weatherapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherappcontainer
  labels:
    app: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherappcontainer
        image: rehanalhasan/weatherapp:latest
        ports:
        - containerPort: 80
---
# WebApiApplication Deployment
# --------------------
# - Deployment to launch 2 containers of rehanalhasan/webapiapplication:latest in a pod.
# - Service (type: LoadBalancer) to open up the app to the world (localhost, at least) at port 8080.
#
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: webapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapicontainer
  labels:
    app: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapicontainer
        image: rehanalhasan/webapiapplication:latest
        ports:
        - containerPort: 8080
---