# WeatherApp Deployment
# --------------------
# - Deployment to launch container of rehanalhasan/weatherapp:latest in a pod.
# - Service (type: LoadBalancer) to open up the app to the world (localhost, at least) at port 80.
# 
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  labels:
    app: weatherapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    nodePort: 30002
    protocol: TCP
  selector:
    app: weatherapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherappcontainer
  labels:
    app: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherappcontainer
        image: rehanalhasan/weatherapp:latest
        ports:
        - containerPort: 80
---
# WebApiApplication Deployment
# --------------------
# - Deployment to launch 2 containers of rehanalhasan/webapiapplication:latest in a pod.
# - Service (type: LoadBalancer) to open up the app to the world (localhost, at least) at port 8080.
#
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: webapi
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: webapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapicontainer
  labels:
    app: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapicontainer
        image: rehanalhasan/webapiapplication:latest
        ports:
        - containerPort: 8080
---
#WeatherApp MySQL Database
apiVersion: v1
kind: Service
metadata:
  name: webapi-mysql
  labels:
    app: webapi
spec:
  ports:
    - port: 3306
  selector:
    app: webapi
    tier: mysql
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapi-mysql-pv-claim
  labels:
    app: webapi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: webapi-mysql
  labels:
    app: webapi
spec:
  selector:
    matchLabels:
      app: webapi
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapi
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: webapi-mysql-pv-claim
---
